# Generated by Django 5.0.6 on 2024-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Title', models.CharField(choices=[('python', 'Python'), ('react', 'React'), ('flutter', 'Flutter'), ('django', 'Django'), ('php', 'Php')], max_length=45)),
                ('Course_Code', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Desc', models.TextField()),
                ('Start_Date', models.DateField(auto_now=True)),
                ('End_Date', models.DateField()),
                ('is_available', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=45, verbose_name='First name')),
                ('Last_name', models.CharField(max_length=45, verbose_name='Last name')),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('DOJ', models.DateField(auto_now=True, verbose_name='Date of Joining')),
                ('Contact', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('teaching', 'Teaching'), ('development', 'Development')], max_length=40)),
                ('is_available', models.BooleanField(default=True, verbose_name='Active Status')),
                ('linked_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=45, verbose_name='First name')),
                ('Last_name', models.CharField(max_length=45, verbose_name='Last name')),
                ('Price', models.IntegerField()),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('DOJ', models.DateField(auto_now=True, verbose_name='Date of Joining')),
                ('Contact', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
