# Generated by Django 5.0.6 on 2024-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('cloth', 'Cloth'), ('electronics', 'Electronics'), ('digital', 'Digital'), ('stationery', 'Stationery')], max_length=40)),
                ('Name', models.CharField(max_length=40)),
                ('Desc', models.TextField()),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, verbose_name='Name')),
                ('Phone', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Website', models.URLField()),
                ('is_Active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Address', models.TextField()),
                ('Capacity', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra_large')], max_length=30)),
                ('Manager', models.CharField(max_length=40)),
                ('Contact', models.BigIntegerField()),
            ],
        ),
    ]
